stages:
  - build
  - linter
  - test
  - deploy

# Etapa 1: Validação estática de sintaxe e boas práticas
django_linter:
  stage: linter
  image: python:3.11-slim
  script:
    - pip install django
    - python manage.py check

# # Etapa 2: Simulação de montagem do Banco de Dados simulando o ambiente produtivo
#django_migrations_test:
#  stage: test
#  image: python:3.11-slim
#  script:
#     - pip install -r requirements.txt
#     - python manage.py makemigrations --check --dry-run
#     - python manage.py migrate --noinput

automação_build:
  image: alpine
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - touch build/info.txt

teste:
  stage: test
  image: mcr.microsoft.com/playwright:v1.49.1-noble
  variables:
    APP_BASE_URL: 'http://127.0.0.1:8000/admin'
    DJANGO_ALLOW_ASYNC_UNSAFE: "true"
  before_script:
    # 1. Atualiza os pacotes e garante que o Python e o pip estejam instalados na imagem do Playwright
    - apt-get update && apt-get install -y python3 python3-pip python3-venv

    # 2. Cria e ativa um ambiente virtual (opcional, mas recomendado para isolamento)
    - python3 -m venv .venv
    - source .venv/bin/activate

    # 3. Instala as dependências do Python (Django, Pytest, plugin do Playtest, etc.)
    # Se você tiver um arquivo requirements.txt, use: pip install -r requirements.txt
    - pip install django pytest pytest-playwright

  script:
    # 4. Executa o arquivo de teste diretamente usando o pytest
    - pytest test_mecanica.py