stages:
  - build
  - test
  - deploy

automação_build:
  image: alpine
  stage: build
  script:
    - node --version
    - npm --version
    - echo "Building"
    - mkdir build
    - touch build/info.txt