[pytest]
# Aponta para o arquivo de configurações dentro do módulo correto
DJANGO_SETTINGS_MODULE = src.settings

# Informa ao pytest que ele deve incluir a pasta 'src' ao procurar pelos códigos
pythonpath = src

# Padrões de nomes de arquivos que o pytest vai buscar para rodar os testes
python_files = tests.py test_*.py *_tests.py
django_find_project = true