# Generated by Django 5.2.15 on 2026-06-27 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Conserto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_carro', models.TextField(verbose_name='Problema Relatado')),
                ('pecas_a_trocar', models.TextField(blank=True, null=True, verbose_name='Peças a serem trocadas')),
                ('data_entrada', models.DateTimeField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('mecanico_responsavel', models.CharField(max_length=100, verbose_name='Mecânico Responsável')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor das Peças')),
                ('valor_servico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Serviço')),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consertos', to='src.automovel', verbose_name='Automóvel')),
            ],
        ),
        migrations.AddField(
            model_name='automovel',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automoveis', to='src.motorista', verbose_name='Proprietário/Motorista'),
        ),
    ]
